### ISSUE TITLE
Stop spam coming over legal_notice

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands-website#287]
Spam coming over the wl.widelands.org/legal_notice should be prevented.

The easiest thing would be to prevent sending mails if the body contains external links, except launchpad, github or widelands.org. Maybe we should redirect to a page saying "We do not accept links in in our contact form" then.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-10-23T08:30:35Z
 * owner: franku
 * the launchpad url was https://bugs.launchpad.net/bugs/1799375

**Comment by gunchleoc** [comment]
(by gunchleoc)
How about using spam keywords, just like we do on the forum?

We could also add recaptcha.

**Comment by gunchleoc** [comment]
(by franku)
Spam coming from legal notice are different than spam in the forums. E.g. they contain bitly links which can't be used as keywords, because they differ a lot.

Since we point to the legal notice page in our privacy policy, if some one don't want to use the google recaptcha for registering, adding the recaptcha to legal notice isn't good. Except we make our own captcha...

What's wrong with preventing urls for legal notices?

**Comment by gunchleoc** [comment]
(by franku)
Of course we can use 'bit.ly' as a keyword for our spam filter... Trying to use the brain on the day after Sylvester may lead into errors :-D

**Comment by gunchleoc** [comment]
(by gunchleoc)
We could also add a mandatory subject line - this will allow us to identify spam messages that got through to our inboxes more easily, because we can delete most of them without opening them.

**Comment by gunchleoc** [comment]
(by franku)
I have created a new app 'quiz_captcha' which is like a quiz: A user has to answer a (widelands) specific question. If the answer didn't match the question, the validation fails. The questions and corresponding answers can be set through the admin interface. E.g. (Question | Answer):

What is the name of the game? | widelands
Smallest barbarian military building? | sentry
Smallest atlantean military building? | guardhouse
How many tribes can you play? | 4
Name of available tribe beginning with A? | Atlanteans

But i am running out of ideas for more question | answers. Any suggestions?

**Comment by gunchleoc** [comment]
(by gunchleoc)
I think these are sufficient - we will have to come up with new ones when these get cracked, so it's better not to have too many.

**Comment by blotter** [comment]
#385 done
