### ISSUE TITLE
Allow tar.gz files in attachments

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands-website#309]
I am uploading the last tournament's replay files to the forums. One of them has been compressed as .tar.gz and I can't upload it, so I'll have to unpack and repack it.

**Comment by frankystone** [comment]
As far i know windows can handle zip files out of the box, but one will need an additional program to decompress tar.gz files.

I am not sure if we should force users to install additional programs.

**Comment by gunchleoc** [comment]
Good point.
