### ISSUE TITLE
Outdated Wiki Pages

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands-website#323]
There are a lot of pages in the Widelands website wiki that are way outdated, in many cases by years. But most times there is no indicator to see that. 
Especially outdated manual pages will easily confuse new users in search of documentation because the content is often plainly wrong regarding the current Widelands version. (e.g. [this page](https://www.widelands.org/wiki/GameHelpmilitaryAndWarfare/) was last overhauled 10 (!) years ago but looks like it is still accurate)

I don't know if this is feasible and how much effort it would be, but IMHO it would be good if wiki pages would automatically be marked as outdated in the header if the last update was more than e.g. six months ago, like:

---
## Outdated
This wiki page was last updated x years ago and may no longer represent the current state of Widelands. If you are familiar with this topic, please consider updating and improving this page.

---

And there should be a link to a list of all outdated pages (sorted by least recently updated) so users willing to improve the wiki can easily see what needs to be fixed most urgently.

**Comment by gunchleoc** [comment]
Excellent idea :)

**Comment by frankystone** [comment]
This was on my wish list for a long time. I think django-tagging, which we have already as a dependency, is the thing which could be used for this kind of stuff.

https://django-tagging.readthedocs.io/en/develop/

Afaik the tagging app is only used for our news section, but it is not used allot for the news.
