### ISSUE TITLE
Filtering and ordering on maps page

### ISSUE THREAD

**Issue by asmaps** [widelands/widelands-website#325]
I am missing a possibility to filter and order the maps on the website differently than just by upload date (e.g. order by rating, filter for required versions, names, author etc). I'd be glad helping implement it. I already found the parts in the code and could make a PR if there are not already bigger plans or a completely new version somewhere in the shelf? Also nowadays class-based views are the way to go in django, so if you don't mind I'd switch to those in the parts that I touch.

Any advice on things to obey is welcome :-)

**Comment by frankystone** [comment]
Hi asmaps :-)

It would be great if you can work on every part of the website ;) Currently there is no active developer for the website stuff, so no big plans. Feel free to provide a PR if you think your changes are ready. For testing purposes we have also a test-website where one can test the code changes in a live environment.

Class based views are a bit complex, but as you said: this is the way to go. 

Just start working and if you run into questions, feel free to ask :)

**Comment by asmaps** [comment]
Ok cool :-) Got it up and running and was asking myself if there are some fixtures/dummy data to put into my local database?
Are you reachable via IRC or similar?

**Comment by frankystone** [comment]
Unfortunately there are no dummy data or fixtures.

I think you are a native german speaker, so i will try to be on the german IRC channel of widelands: #widelands-de on freenode. But currently i am very busy with real live... Maybe best to ask here, or in our forums on www.widelands.de
