### ISSUE TITLE
https://www.widelands.org/webchat/ does not show on Firefox 75.05

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands-website#329]
I can not use the Webchat any longer with Firefox 75.95
The page https://www.widelands.org/webchat/  is just blank.

I use a Scriptblocker and and Ad-Blocker, but disabling this does not help.
Chrome and Safari have no Issues.

**Comment by frankystone** [comment]
No Problem here with firefox 75 on archlinux.

That page is using the webchat provided by freenode. It is just displayed inside an iframe, afaik. This is the same as using  https://webchat.freenode.net/ directly with the difference that the channel #widelands is preconfigured. Do have also problems to use this link directly?

**Comment by klaus-halfmann** [comment]
Mhh, Freenodes works, directly and if I show the frame from widelands.org. ?
Can we put this on hold till the next FF release is out, or such?

**Comment by frankystone** [comment]
> Mhh, Freenodes works, directly and if I show the frame from widelands.org. ?

Don't know how i should interpret the question mark. Can you please be more descriptive?

> Can we put this on hold till the next FF release is out, or such?

Of course. Currently i have no time at all.

**Comment by frankystone** [comment]
On ff version 76 it works also for me.

**Comment by frankystone** [comment]
Is this is still a problem for you?

**Comment by gunchleoc** [comment]
Working for me too. The chat does do some checks that will need some JavaScript, so make sure you're not blocking it.

**Comment by frankystone** [comment]
No reaction -> closing
