### ISSUE TITLE
Add-on server

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands-website#330]
See https://github.com/widelands/widelands/issues/3898

There are plans for an add-on system for Widelands. The server will have to provide an interface so Widelands can down-and upload add-ons.

(Disclaimer: I have no networking experience and can not imagine how such a back-end would look like in practice, nor estimate the programming effort)

**Comment by frankystone** [comment]
Shouldn't this be an issue of [widelands/meatserver](https://github.com/widelands/widelands-metaserver) instead of widelands/website?
