### ISSUE TITLE
Unable to download map

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands-website#332]
When I try to download the map ["Felsige Wälder"](https://www.widelands.org/maps/felsige-walder/) it fails with an "Internal Server Error". All other maps work.

Right-clicking on "Download" and choosing *Ziel speichern unter* gives me an HTML file with this content:
```
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

Using Firefox 79.0 on Ubuntu MATE 20.04, 64-bit

**Comment by stonerl** [comment]
Seems to be an issue with the Umlaut.

**Comment by frankystone** [comment]
This should not happen since the [bug](https://github.com/widelands/widelands-website/issues/7) was fixed.

The download count counts 32 downloads, not sure if this can be true...

**Comment by frankystone** [comment]
Something is going wrong there, just tested it.

Will inform _Elefantenrennen to rename his map and upload again meanwhile i delete the map.

**Comment by gunchleoc** [comment]
I'm attaching the error log

[django-error-332-log.txt](https://github.com/widelands/widelands-website/files/5085301/django-error-332-log.txt)

**Comment by frankystone** [comment]
I got the error log also :-)

The path of the map was stored correctly in the database (looked into the admin page) and the file exists in filesystem. The [locales](https://www.widelands.org/locale) on the server are also correct.

**Comment by frankystone** [comment]
I can't reproduce this locally...

**Comment by frankystone** [comment]
Can someone send a map saved with build 21?

**Comment by frankystone** [comment]
After reading the errorlog again there is no need to send a map made with build 21.
