### ISSUE TITLE
Registering and Password Reset not sending confirmation e-mail

### ISSUE THREAD

**Issue by xorxsan** [widelands/widelands-website#340]
I've been trying to create a user for the website to post some game suggestions but to no avail. Neither the register nor the password reset functionalities send me activation e-mail or the e-mail with instruction respectively (I've checked the spam folder but the e-mail is not there).

Thanks!

**Comment by stonerl** [comment]
It’s working for me. Can you tell me the username you tried to register?

**Comment by xorxsan** [comment]
Yes, I tried to register xorx as a username.
Thanks!

**Comment by stonerl** [comment]
I activated your account. I hope you remember your password. You should consider using a different mail-address, hotmail is kind of a mess.
