### ISSUE TITLE
Broken link on ProductionSiteProgramReference page

### ISSUE THREAD

**Issue by xorxsan** [widelands/widelands-website#341]
Navigate to https://www.widelands.org/wiki/ProductionSiteProgramReference/
Click on the **Current version on trunk** link (which points to http://bazaar.launchpad.net/~widelands-dev/widelands/trunk/view/head:/doc/productionsite_program_reference.xhtml)
404

**Comment by Noordfrees** [comment]
Thanks for reporting, I fixed the link
