### ISSUE TITLE
Missing terain

### ISSUE THREAD

**Issue by Rian190** [widelands/widelands-website#346]
Build 21 on ubuntu

When trying to startup  https://www.widelands.org/maps/lesser-ring-12/

I get the error: 

![image](https://user-images.githubusercontent.com/76522776/109437995-17b5c100-7a28-11eb-8579-7d476d5b05dc.png)

**Comment by Niektory** [comment]
The website says "This map requires a version of Widelands build 21 or newer!". But the map doesn't work in Build 21, only in current master.

This is the content of the `version` file in the map:
```
# Automatically created by Widelands 1.0~git25123[e32d698@master] (Release)

[global]
map_source_url=
map_release=
map_creator_version="build-20"
map_version_major="0"
map_version_minor="12"
map_version_timestamp="1610360750"
packet_version="1"
packet_compatibility="1"
needs_widelands_version_after="20"
```
So perhaps this is not a problem with the website, but wrong information saved in the map. Not sure what to do about this.

**Comment by Noordfrees** [comment]
The maps that were already saved with this wrong information will keep showing it. We should get https://github.com/widelands/widelands-website/pull/344 & https://github.com/widelands/widelands/pull/4646 merged soonish to prevent more maps being saved with wrong info. 

I wonder if it would be possible to adjust the information contained in the already uploaded faulty maps manually?

**Comment by Rian190** [comment]
Since https://github.com/widelands/widelands/pull/4646 has been merged I assume this ticket can be closed as well?

**Comment by frankystone** [comment]
Yep :-)
