### ISSUE TITLE
Cleanup users profile

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands-website#358]
Currently there are some columns in a users profile which are not used much:

Website:
Jabber:
ICQ:
MSN:  
AIM:
Yahoo:

I would suggest to remove those and add an additional entry `Operating system`. Maybe also `IRC nick`.

The resulting profile would then show this informations:

Joined:
Forum Posts:	
Location:
Operating System:
IRC Nick:
Signature:

Also related is #296

**Comment by klaus-halfmann** [comment]
* Maybe some generic "URL" would be OK? 
* "IRC Nick" could be Nick (IRC, Discord, ...)

**Comment by frankystone** [comment]
> * Maybe some generic "URL" would be OK?

Should be considered. Some statistics:
Overall users: 4514
Has filled 'Website': 395
'Website' contains suspicious links (containing 'escort', 'girl', 'gold', 'libido' and so on: > 12 

Although such links can't be gathered by search engines, i think we shouldn't allow such links on the website. One can use the Signature for this, with the advantage that a forum moderator can see it immediately and remove it (or the user).

> * "IRC Nick" could be Nick (IRC, Discord, ...)

`Nickname/Service:` would be fine, imho.

**Comment by frankystone** [comment]
![profile](https://user-images.githubusercontent.com/6730556/204620308-5240c706-e93b-4b7d-8560-1ed3c96cd7d5.jpg)

**Comment by Noordfrees** [comment]
What about the user's version of Widelands? Along with the OS one of the most important infos for technical help.

**Comment by frankystone** [comment]
Good point. Although i am not sure if the widelands version will be kept up to date.

Anyway it is no Problem to add such a  field to the db :-)

**Comment by frankystone** [comment]
Added a field to enter widelands version.

Made also some tweaks to the view after registration has completed: https://github.com/widelands/widelands-website/pull/394/files#diff-fd75fc2de36ec53f31e2687cc09c687aa03990bd2011562a7a4fc46bee711725

**Comment by frankystone** [comment]
Should we change something here?

![profile_forum](https://user-images.githubusercontent.com/6730556/204866816-5df064dc-1fa7-49e5-b940-9de0dffb388e.jpg)

**Comment by frankystone** [comment]
closed by #394
