### ISSUE TITLE
Add settings to disable add-on related e-mail notifications

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands-website#359]
The add-ons server sends e-mail notifications to add-on authors to inform them about new Transifex string issues in their add-ons. As of my next branch it also sends a mail when a maintainer deletes your add-on.
Like all e-mail notifications this should be configurable under https://www.widelands.org/notification/. The server already reads in the `notification_noticetype` and `notification_noticesetting` tables to discover whether this setting exists and if so whether a user has disabled notices. (Default is to assume they're enabled.) The notice type labels are assumed to be called `addon_transifex_issues` and `addon_deleted` respectively. What's left to do is to add the settings to the website

**Comment by frankystone** [comment]
This is a difficult task. The notification app is tied to emailing from the website-server. It is not possible without much effort to use this app for email-settings regarding the add-ons server (for mails send by the add-ons server).

To archive this the model(s) and codebase of the notification app needs to be heavily adapted.

Maybe a better approach is to create a new app `wladdons_settings` or so. As far i understand you just want to know if users want emails from the addons-server, or not. So just a boolean...

**Comment by frankystone** [comment]
Fixed by #374
