### ISSUE TITLE
feed https://www.widelands.org/feeds/news/ is broken yielding "The document you requested could not be found. You went astray somewhere... "

### ISSUE THREAD

**Issue by okurz** [widelands/widelands-website#376]
The last time I successfully an entry for the feed was in 2018, though this was with the URL https://wl.widelands.org/feeds/news/

**Comment by frankystone** [comment]
Sorry, the url was changed in September 2018. See [this thread](https://www.widelands.org/forum/topic/4483/)
A list of all available feeds can be found here: https://www.widelands.org/wiki/ContactPage/

We should add a redirect, so i leave this bug open.
