### ISSUE TITLE
Add Deadlock to Tips and Tricks: Nothing gets built

### ISSUE THREAD

**Issue by Wuzzy2** [widelands/widelands-website#377]
I have discovered a type of deadlock that is not covered by in the Tips and Tricks section of the website, and I suggest to add it.

This is how it works:

If you have a large number of building sites, it can happen that nothing gets built forever, even if some building sites have all required supplies.

It seems the reason for this is that once builders have walked to a building site, they wait on this building site forever. So if all building sites are those that are currently "stuck" (missing supplies) are those with a builder on it, and you have no more builders, your economy is deadlocked.

It seems that once a builder has decided on a building site, they stick to it forever, even if there is nothing to do for literal hours, and even if there are other building sites with 100% supplies. Meaning, you economy can deadlock even if you have all the required goods.

The only way I found to resolve this is to completely destroy a few of the incompete building sites to force the builders to move to a different location.

This happened to me in the Atlantean campaign mission 1 in v1.0 because I have created a lot of building sites but ran out of cloth. And the spider farm was never being built altough it had 100% supplies bcause there was no builder on it and all builders were doing nothing on all the other building sites (which required cloth). I sped up 100× but it was useless then I randomly demolished one of the building sites and suddenly everything started working again.

**Comment by Noordfrees** [comment]
It's a wiki page, so please do feel free to go ahead and add this info :)
https://www.widelands.org/wiki/edit/Tips%20and%20Tricks/
https://www.widelands.org/wiki/Tips%20and%20Tricks/

**Comment by frankystone** [comment]
This issue is not related to the website source code, closing.
