### ISSUE TITLE
paypal link missing

### ISSUE THREAD

**Issue by andy5995** [widelands/widelands-website#379]
At the bottom of https://www.widelands.org/wiki/Game%20Manual/

>The link above on the right will bring you to the Paypalsite.

But I didn't see any link

**Comment by frankystone** [comment]
It's a wiki, so you can edit the pages.

I've removed the sentence.

**Comment by andy5995** [comment]
I thought the problem was that the paypal link was supposed to be in the upper right navigation menu, not just that the sentence needed to be removed.

So.. what does that mean? WL doesn't accept donations through paypal anymore?

**Comment by frankystone** [comment]
OpenSource projects used to have a paypal button somewhere and widelands had this also some time ago. There where several people who wanted to contribute by spending some money, but don't had a paypal account and don't wanted to create such an account. So in the end the decision was made to remove the paypal button and one of our elders took the freedom to pay the server costs.
